### ISSUE TITLE
您好，请问gen_disambiguation.py中的train_pre.json文件在哪？

### ISSUE THREAD

**Issue by bit-kop** [Pelhans/Entity_Linking#1]
您好，请问gen_disambiguation.py中的train_pre.json文件在哪？

**Comment by Pelhans** [comment]
那个是根据规则处理过的文件，移除一些有问题的数据，比如重复、格式不对。可以直接用 train.json，两个格式是一致的

**Comment by bit-kop** [comment]
好的，知道了，谢谢老师


| |
李小超
|
|
邮箱：liverpoolkopxiaoli@163.com
|

签名由 网易邮箱大师 定制

在2020年11月11日 22:38，Pelhans 写道：

那个是根据规则处理过的文件，移除一些有问题的数据，比如重复、格式不对。可以直接用 train.json，两个格式是一致的
